### ISSUE TITLE
Back to VPN problems again

### ISSUE THREAD

**Issue by kirk-kerekes** [alterstep/dnscrypt-osxclient#110]
DNSCrypt used to recover after my VPN shut off, but now it doesn't. 
If I disable DNSCrypt and then re-enable it, it runs normally.

**There seems to be a time element involved** -- if the VPN has only run for a little while (less than an hour, say) DNSCrypt recovers essentially _instantly_. 

If the VPN has run for most of a day, DNSCrypt gets stuck in disabled mode, and has to be disabled/re-enabled.

I am using Viscosity (on macOS) to manage the VPN, is there some setting in its profusion of settings that would enhance the behavior of DNSCrypt?

**Comment by pilldriver** [comment]
You should disable your DNS settings in Viscosity that get pushed by your VPN provider. 

You can do this by going into Viscosity's Preferences > select the VPN Connection > Click "Edit" down right > go to "Networking" > Then at the "DNS Settings" part of "Networking" > Select "disabled " from the dropdown.

This way DNSCrypt doesn't have to fight with the VPN for who owns your local DNS settings.

**Comment by kirk-kerekes** [comment]
That worked. 

DNSCrypt continues to function while the VPN is running. Interesting.

Thank you!

So this method uses DNSCrypt through the tunnel, right? The DNS inquiries are encrypted through the far end of the tunnel and on to the DNSCrypt server? 

I notice that Viscosity has several options on DNS — “automatic” (which is what I previously had) and some that specify different ways of specifying which DNS gets used for VPN and non-VPN traffic. Are there any other than “disabled” that will cooperate rather than fight with DNSCrypt?

And, on a perhaps unrelated issue, (and nothing really to do with DNSCrypt, AFAIK) I notice that Viscosity is reporting a private address in its menu, instead of the VPN public address. 

I have an inquiry in to the Viscosity folk about that, but I was wondering if you had any wisdom to shed on it.

Here are the screenshots I sent to the Viscosity folks:



iStat Menus shows both addresses: the correct VPN public IP address, and one for tap0 with the 10.10.10.20 private address.



Thanks again!

**Comment by pilldriver** [comment]
Yes your DNS is routed through your VPN, you can/should also enable "Send all traffic over the VPN connection". This way there should be no IP leakage or whatever when viscosity is active. 

Also because we are using DNSCrypt as default DNS provider you should keep the VPN DNS disabled so you are 100% sure everything gets resolved through DNSCrypt. Better keep it simple so when in trouble you know where to look. 

The private address in Viscosity is just the internal address you get from your VPN provider, just like your home network (192.168.x.x). This is normal behaviour, you connect to the VPN gateway and this does a passthrough to the web which can be a cluster of servers with different ip's. It all depends on how the VPN provider do their setup.

As last, probably iStat does u curl against a service like 'curl ifconfig.co' but we are getting way offtopic here and has nothing to do with DNSCrypt ;)

**Comment by GitTheHellOutaHere** [comment]
FWIW, I also use DNSCrypt with Viscosity. I only use Viscosity with OpenVPN - no paid services.
When I disconnect from a VPN server, DNSCrypt re-connects within seconds.

In all my Viscosity server settings I had enabled **Send all traffic over VPN connection**.
I had also set the **DNS Settings Mode** to Full DNS.

Maybe I was wrong, but I thought that would further hide my DNS activity by forcing it to go through the VPN’s DNS server.

Since I haven’t had any issues using those settings, I’m wondering how changing them to the ones suggested by pilldriver and kirk-kerekes might benefit me.

i.e. disable **Send all traffic over VPN connection** and change **DNS Settings Mode** to Disable.

**Comment by alterstep** [comment]
it's not for use with a VPN

**Comment by GitTheHellOutaHere** [comment]
As I said,

> I have also set the DNS Settings Mode to Full DNS.

>Maybe I was wrong, but I thought that would further hide my DNS activity by forcing it to go through the VPN’s DNS server.


As I understood from Viscosity’s instructions, I thought forcing DNS lookups to go through the overseas OpenVPN server’s DNS would provide more protection than routing them through a US DNS server if that’s what I’m using.
Seems like that would provide better anonymity by making it look like the computer in Malaysia, China or wherever was actually making the DNS requests instead of mine.
If that’s not correct, then someone please let me know why.

> **Full DNS**
Viscosity will setup your Mac or PC so your VPN DNS servers are used for all requests. **This option is preferred when all traffic is routed over the VPN Tunnel** to ensure consistency of browsing and using applications in this configuration, as well as preventing DNS Leaks when this is required.
