### ISSUE TITLE
Standby only with dnscrypt-osxclient-1.0.13

### ISSUE THREAD

**Issue by pjcoxgcsyd** [alterstep/dnscrypt-osxclient#134]
Updated to latest version, dnscrypt-osxclient-1.0.13. I only see "Standby" despite disabling, enabling, uninstalling with AppDelete, restarting and reinstalling. I uninstalled again using AppDelete and installed dnscrypt-osxclient-1.0.12, restarted and see that DNSCrypt now stays Enabled.

**Comment by mitchelhaan** [comment]
I had the same issue. I was hoping to capture something in the debug log that would help, so I enabled debugging by running `touch "/Library/Application Support/DNSCrypt/control/debug.enabled"`. (The control directory was empty prior to creating debug.enabled) When I tried enabling it again, it magically worked. Note that I have the OSX Firewall enabled and I didn't get a prompt to allow connections for dnscrypt-proxy until after I had created the debug.enabled file and re-enabled DNSCrypt.

**Comment by pjcoxgcsyd** [comment]
Did that. Uninstalled, restarted, installed1.0.13. Saw same behaviour. I'll stick with 1.0.12 for the time being. It works.

**Comment by Thireus** [comment]
Which MacOS version?

**Comment by pjcoxgcsyd** [comment]
Running 10.11.6, El Capitan. I will download and try again.

**Comment by alterstep** [comment]
Look at the new FAQ! https://github.com/alterstep/dnscrypt-osxclient/blob/master/FAQ.md

**Comment by phillycheeze** [comment]
Happening with me also on 10.12

Uninstalled, reinstalled, and the same thing. It is enabled but says "Not using DNSCrypt" for any name server I choose.

**Comment by pjcoxgcsyd** [comment]
Uninstalled 1.0.12 using the About > Uninstall option under Prefs. Downloaded and installed 1.0.13, restarted, and now it works fine. (I am still on macOS 10.11.6.)

**Comment by celsoazevedo** [comment]
Even after a manual uninstall/reinstall it doesn't work for me if the "disable ipv6 to reduce ipv4 latency" option is enabled (tested on 2 machines, 1 with Sierra and 1 with El Capitan).

No issues with the previous version (1.0.12).

**Comment by jedisct1** [comment]
@celsoazevedo Did you try different resolvers?

**Comment by celsoazevedo** [comment]
@jedisct1 Yes. OpenDNS, Adguard, dnscrypt.eu/org, etc. Only works if that option is disabled.

**Comment by carltonfsck** [comment]
I'm experiencing the same issue with the new 1.0.13 update on OSX 10.11.6 (El Capitan).  

I tried uninstalling, then restarting, then reinstall 1.0.13 again.  It seems to work for a moment then it will stop working altogether.  I tried changing to different resolvers but this had no effect.  

I initially thought it was my antivirus (Latest version of 'Comodo Antivirus for Mac') causing issues, as alterstep had mentioned in the FAQ: 

https://github.com/alterstep/dnscrypt-osxclient/blob/master/FAQ.md  

However, after some trial & error of disabling my antivirus, as well as Little Snitch, I'm still having the issue.  

What I am noticing is that whenever I enable DNSCrypt it will say "Using DNSCrypt" and will show the green shield.  But when trying to browse to websites, trying to ping the hostname or performing DNS lookups via terminal, they fail and/or error out.  Unfortunately, the status of DNSCrypt never changes.  It still says "Using DNSCrypt".  This is very misleading.  If you leave DNSCrypt enabled for a long time, it will eventually go to "Standby", but you can't do any DNS lookups, etc.

Here's a copy/paste of terminal when I attempt to ping Google or perform a DNS lookup with DNSCrypt enabled:

[Carltonfsck@MacBook-Pro:~ ] $ ping google.com
ping: cannot resolve google.com: Unknown host
[Carltonfsck@MacBook-Pro:~ ]


[Carltonfsck@MacBook-Pro:~ ] $ dig google.com

; <<>> DiG 9.8.3-P1 <<>> google.com
;; global options: +cmd
;; connection timed out; no servers could be reached
[Carltonfsck@MacBook-Pro:~ ] $

As soon as I disable DNSCrypt I can not only ping with the hostname (DNS resolves hostname successfully), but I can also perform DNS lookups, as it will revert to your local DNS settings.

I may end up going back to 1.0.12 temporarily until this issue is identified and/or resolved.  I love this app and I don't want to go a day without using it.  

Hope my input helps?


Regards,

--Carltonfsck

**Comment by jedisct1** [comment]
I think the issue is not specifically with disabling IPv6, but with all plugins using ldns.

OSClient ships with a really old version of ldns, probably because it was required to support old macOS versions. But the proxy was linked against a new version of ldns.

People having a system with their own copy of ldns (for example because they are using Homebrew) have no problems starting the proxy via OSXClient. People who don't can't use these plugins.

**Comment by alterstep** [comment]
thank you for pointing to the right direction. ldns needs openssl, and the installed openssl version vary greatly from one system to another.

I released a new version that doesn't use openssl.

try 1.0.14 everyone
