### ISSUE TITLE
How do I work this thing!

### ISSUE THREAD

**Issue by boozedog** [alterstep/dnscrypt-osxclient#20]
I installed v1.0.3 and also installed dnscrypt-proxy 1.3.3 using brew.

The dnscrypt-osxclient icon is gray, and I'm able to check and un-check Enable DNSCrypt, but when I click the DNSCrypt-OSXClient Preferences menu item, nothing happens.

I tried turning on dnscrypt using the following command: 
`dnscrypt-proxy --daemonize --provider-name=opendns`
but no idea if that had any effect. It certainly didn't change any of the behavior of the DNSCrypt-OSXClient menu.

Halp!!

**Comment by ryapeter** [comment]
Hi Just want to bump this because I suddenly have the same problem.

I am using it without no problem for a month and decide to check my ISP default DNS. After turning everything back to crypt. It stuck on standby.

Please let me know what to try.

**Comment by Mr-Magoo54** [comment]
*Bump*

**Comment by Mr-Magoo54** [comment]
![b73-fkqigae_iib](https://cloud.githubusercontent.com/assets/12439099/7762982/14b74fe6-ffef-11e4-8e7b-a0c09070bff3.jpg)

Hellooooo? Mrs. Pommelhorse?

....

I'd like to get down now....

**Comment by alterstep** [comment]
Can you try the new version 1.0.6?

**Comment by boozedog** [comment]
It's working! What changed?

**Comment by mehronkugler** [comment]
The OSX client doesn't seem to automatically change my DNS server list to point to 127.0.0.54. 

When I manually add 127.0.0.54 to my list of DNS servers in System Preferences > Network Settings > Advanced, the DNSCrypt client status changes from red shield (Standby) to green (Using DNS Crypt).

Anytime I change it away from 127.0.0.54, the client doesn't appear to be able to change it back.

Is this intended?

**Comment by alterstep** [comment]
Hi there,

Do not manually change the DNS settings; this is what the client is for!

It will change the settings to 127.0.0.54 after having verified that the chosen configuration actually works. If not, it will keep the previous settings, and keep trying in the background.

So, it didn't make the changes because DNSCrypt doesn't work.

On thing you can do is create a file (the content is not important) named `debug.enabled` in `/Library/Application Support/DNSCrypt/control`.
This will then log debugging messages in `/var/log/dnscrypt-osxclient-debug.log`.
