### ISSUE TITLE
DNSCrypt constantly in Standby since OS X 10.11 Beta 4 (15A226f)

### ISSUE THREAD

**Issue by Nomis101** [alterstep/dnscrypt-osxclient#58]
Since I've updated OS X 10.11 to Beta 4 (15A226f) yesterday, the status of DNSCrypt is permanently in Standby. I've tried to reinstall DNSCrypt for Mac 1.0.9, I've changed the DNS name server and I've flushed the DNS cache. It still does not connect anymore to any DNSCrypt name server. It was all fine in 10.11 Beta 3.

**Comment by alterstep** [comment]
For no reason, Apple removed the lockfile command in this new beta!

But they didn't remove the documentation, so I don't know if the removal is intentional or not. But it breaks the OSXClient scripts because they use this command.

The lockfile command code is in procmail, so the source code is available. I can recompile it and add a copy to the package. Removing things without any prior notifications is not nice from Apple.

**Comment by alterstep** [comment]
Yes, this is it. Re-adding the tool Apple removed in this new beta fixes it.

I have to do more testing, and I will release a new version.

**Comment by alterstep** [comment]
I released 1.0.10, which is compatible with the new OSX beta.

**Comment by Nomis101** [comment]
I can confirm, that this is fixed now. Thanks for fixing this that fast! And you are right, its not nice from Apple removing this without any prior notifications.
