### ISSUE TITLE
Should I disable firewall on my Mac when using DNSCrpyt?

### ISSUE THREAD

**Issue by FrankZhang002** [alterstep/dnscrypt-osxclient#59]
Hi, I'm using Mac OS 10.10.4 and DNSCrpyt 1.0.9. I want to know that do I need to disable my firewall when using DNSCrpyt? Is mac firewall affect DNSCrpyt? 

Thank you.

**Comment by alterstep** [comment]
You can leave the firewall on. Uncheck "Block all incoming connections" because checking it is going to cause a lot of problems even without dnscrypt.

Then first time you run dnscrypt with the firewall on, it will ask you to authorize the application called dnscrypt-proxy. Click "always", this is safe and this is the only thing you will have to do!

**Comment by alterstep** [comment]
Now that I think about it, you may have to allow the "hostip" application, too.
