### ISSUE TITLE
What is the correct entry for "Bypass DNSCrypt to resolve domain"

### ISSUE THREAD

**Issue by lordonsen** [alterstep/dnscrypt-osxclient#69]
The problem is when I'm doing local development it will become terribly slow because of the dns lookup even when using IP address. The only way I can do right now is to disable DNSCrypt.

1. How to bypass IP address ?
a. 192.168.1.1 (Individual IP)
b. 192.168.1.1/24 (LAN with subnet)
c. 127.0.0.1/24 (Loopback with subnet)
d. IPv6

2. How to bypass domain ?
a. localhost (Loopback)
b. local (domain without dot prefix)
c. .local (domain with dot prefix)
d. *.local (subdomain with wildcard)

3. How to check if bypass is working?
a. nslookup
b. scutil --dns

Which are those are correct?

**Comment by jedisct1** [comment]
This app is only used with DNS queries. It doesn't do anything to connections made directly to IP addresses and doesn't even see them.
So, nothing has to be done in order to keep reaching `192.168.1.1` or any other IP address. The bypass rules are only for DNS names.

In order to bypass dnscrypt for `zone` and `*.zone`, you just need to enter `local` in the list of bypassed names. It always includes other names in the same zone. However, this is not required for `local` which is already in the default list of names that never use dnscrypt.

Do not use `nslookup` for anything; it's broken as a tool to solve DNS issues, and it doesn't use the same resolution procedure as other apps on your system. In particular, it doesn't use the same cache as the rest of the system and doesn't handle per-zone configuration (used for bypassing).

Use a generic command requiring DNS resolution, such as `ping` instead.
