### ISSUE TITLE
hosts file, GUI and apple.com pings..

### ISSUE THREAD

**Issue by zaphodd** [alterstep/dnscrypt-osxclient#97]
if you block apple.com in your HOSTS file, DNScrypt errors, and displays 'X' and keeps trying to respawn. Is dnscrypt-osxclient pinging Apple.com ?  i think poss privacy error perhaps ?

**Comment by pich** [comment]
I think issue is in file start-dnscrypt-proxy.sh line 45: answers=$(exec dig +time=1 +short +tries=2 -p $priority @"$INTERFACE_PROBES" www.apple.com. 
Hardcoding www.apple.com domain in this dig cmd is not a good idea. It is a potential vector of attack that can let bad guys probe if user is using DNScrypt on ISP level - just by blocking connection and watching for dig requests.

**Comment by alterstep** [comment]
This verifies that the DNSCrypt server is operational by asking what the IP address of Apple is. This query is not even sent to Apple, only to the DNSCrypt server.
Why do you block apple.com on a mac? Did you steal it?

**Comment by alterstep** [comment]
I don't understand your vector of attack. ISP doesn't see the content of dnscrypt queries, only encrypted data.

**Comment by 1-61803** [comment]
Since you blocked #98, and #97 is somewhat related, I'll comment here. I checked the [http query](https://github.com/alterstep/dnscrypt-osxclient/blob/master/DNSCrypt-Preference-Pane/DNSCrypt/extra/usr/scripts/check-hijacking.sh#L11-L12) you send via `curl` and you're pretty much contacting Apple. Fortunately, I suppose I can change it in `/Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/scripts/check-hijacking.sh`.

**Comment by zaphodd** [comment]
did i steal it ?  what a disgraceful attitude you display, why do you encrypt DNS ?
you can stick your software.
